fix: add support for mssql_managed_instance
infracost/infracost pull request #2393
Opened 2023-04-02 16:19 UTC by grixxie

addressing issue: #2063

infracost currently supports the "depcrecated" [sql_managed_instance](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_managed_instance) -> add support for new [mssql_managed_instance](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_managed_instance)

any feedback appreciated

2023-04-15 15:30 UTC, grixxie commented
@tim775 I _think_ this is ready for review - I would appreciate some feedback / some guidance on what else is left to do here

2023-04-24 12:52 UTC, tim775 requested changes
Thanks @grixxie this is great!  
I left a few mostly style comments.  
Also we need to add the usage parameters to the [example usage file.](https://github.com/infracost/infracost/blob/master/infracost-usage-example.yml)

Let me know if you have time to make the changes, otherwise I'm happy to finish them off.
Cheers,
Tim

2023-04-24 12:52 UTC, tim775 commented on internal/resources/azure/mssql_managed_instance.go
> +	costComponents = append(costComponents, r.mssqlMIStorageCostComponent(), r.mssqlMIBackupCostComponent())
We should probably only add the storage cost component if it is above the default
```suggestion
	if r.StorageSizeInGb - 32 > 0 {
		costComponents = append(costComponents, r.mssqlMIStorageCostComponent(), r.mssqlMIBackupCostComponent())
	}
```

2023-04-24 12:52 UTC, tim775 commented on internal/resources/azure/mssql_managed_instance.go
> +			Name:           fmt.Sprintf("Compute (%s %d Cores)", strings.ToTitle(r.SKU), r.Cores),
```suggestion
			Name:           fmt.Sprintf("Compute (%s %d cores)", strings.ToTitle(r.SKU), r.Cores),
```

2023-04-24 13:23 UTC, grixxie commented
Thanks for this @tim775 , I will make these changes including the example usage file :)

2023-04-25 11:40 UTC, tim775 approved these changes
Thanks, looks good!  If you would, please update the golden file test to pick up the changes by running:
```
ARGS="--run TestMSSQLManagedInstance -v -update" make test_azure
```

2023-04-25 12:45 UTC, merged

2023-04-25 22:00 UTC, grixxie commented
Hey @tim775 , I'm still pretty new to this so I'd appreciate some help here - running ```make test_azure``` with the above commands is failing and the golden test file produced is showing all $0.00's.

I've followed the steps in CONTRIBUTING.md including the [azure-credentials](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md#azure-credentials) section but still no luck. I'm unsure whether it's a problem with my code changes or my local setup at this point - maybe you can help?

Apologies, still getting into this :laughing:

2023-04-26 02:31 UTC, tim775 commented
@grixxie, no worries I actually ended up merging this with the intention of updating the golde file test after and ran into the same issue you're seeing now.  It looks like the filters got messed up somehow, but it was a [quick fix.](https://github.com/infracost/infracost/pull/2422/files#diff-e13abd66b50877fed0bdd48c862d36d8564d12f5947f38021034d06363d4539f)