Adding basic KMS resource
infracost/infracost pull request #255
Opened 2020-12-04 10:17 UTC by sashman

Fixes #213

Given a key definition:

```
resource "aws_kms_key" "kms" {}
```

Report the basic key usage:

```
 aws_kms_key.kms
  └─ CMK                                                1  months       1.0000       0.0014        1.0000
  Total                                                                              0.0014        1.0000
```

2020-12-05 08:06 UTC, alikhajeh1 requested changes
Thanks @sashman! This is good for key storage, what can be done for key usage? Could the `customer_master_key_spec` and `key_usage` params offer clues as to which of the key usage prices apply? if not, we can just show those 5 prices with no costs so users are aware.

2020-12-05 08:06 UTC, alikhajeh1 commented on internal/providers/terraform/aws/kms_key.go
> +					{Key: "usagetype", ValueRegex: strPtr("/-KMS-Keys/")},
```suggestion
					{Key: "locationType", Value: strPtr("AWS Region")},
					{Key: "usagetype", ValueRegex: strPtr("/KMS-Keys/")},
```
This ensures that if/when AWS Outpost support is added for this resource, the filters still return the price we want.

2020-12-07 11:02 UTC, sashman commented
@alikhajeh1 
> we can just show those 5 prices with no costs so users are aware.

Do you mean like so?
```
  aws_kms_key.kms
  ├─ Customer master key                                1  months         1.0000       0.0014        1.0000
  ├─ Requests                                           -  10k requests   0.0300            -             -
  ├─ Requests (RSA 2048)                                -  10k requests   0.0300            -             -
  ├─ Requests (ECC GenerateDataKeyPair)                 -  10k requests   0.1000            -             -
  ├─ Requests (Asymmetric)                              -  10k requests   0.1500            -             -
  └─ Requests (RSA GenerateDataKeyPair)                 -  10k requests  12.0000            -             -
  Total                                                                                0.0014        1.0000
```

2020-12-08 08:46 UTC, alikhajeh1 requested changes
Thanks @sashman - just a few minor changes needed, plz assign it back to me when you'd like to review/merge it.

2020-12-08 08:46 UTC, alikhajeh1 commented on internal/providers/terraform/aws/kms_key.go
> +	costComponents = append(costComponents, requestPriceComponent("Requests (ECC GenerateDataKeyPair)", region, "GenerateDatakeyPair-ECC"))
```suggestion
	costComponents = append(costComponents, requestPriceComponent("ECC GenerateDataKeyPair requests", region, "GenerateDatakeyPair-ECC"))
```

this matches the AWS pricing page description

2020-12-08 08:46 UTC, alikhajeh1 commented on internal/providers/terraform/aws/kms_key.go
> +	costComponents = append(costComponents, requestPriceComponent("Requests (RSA GenerateDataKeyPair)", region, "GenerateDatakeyPair-ECC"))
```suggestion
	costComponents = append(costComponents, requestPriceComponent("RSA GenerateDataKeyPair requests", region, "GenerateDatakeyPair-ECC"))
```

2020-12-08 08:46 UTC, alikhajeh1 commented on internal/providers/terraform/aws/kms_key.go
> +		costComponents = append(costComponents, requestPriceComponent("Requests (Asymmetric)", region, "Asymmetric"))
```suggestion
		costComponents = append(costComponents, requestPriceComponent("Requests (asymmetric)", region, "Asymmetric"))
```

2020-12-08 08:46 UTC, alikhajeh1 commented on internal/providers/terraform/aws/registry.go
> +	"aws_kms_external_key",
The `aws_kms_external_key` needs the `Customer master key` cost only (no requests). Can you possibly add this as a resource and put the `Customer master key` cost in a function so `aws_kms_external_key` calls that function? See the `elb.go` file for an example of how this was done elsewhere.

2020-12-08 08:46 UTC, alikhajeh1 commented on internal/providers/terraform/aws/registry.go
> +	// AWS KMS
This group should probably go after `// AWS IAM aws_iam_* resources` as we try to keep these grouped alphabetically - both at the group level and at the line-item level, which you've already done :)

2020-12-09 08:46 UTC, merged