feat(aws): add support for AWS fsx windows fs
infracost/infracost pull request #288
Opened 2020-12-19 19:31 UTC by sinabakh

Fix #263

2020-12-19 19:37 UTC, sinabakh commented
We can't support one of the params: `backup storage` so I left its quantity blank. Here is a sample output:
```
✔ Calculating costs

  NAME                                 MONTHLY QTY  UNIT       PRICE   HOURLY COST  MONTHLY COST  

  aws_fsx_windows_file_system.example                                                             
  ├─ Throughput capacity (Multi-AZ)          1,024  GB-months  4.9500       6.9436    5,068.8000  
  ├─ Storage (Multi-AZ - HDD)                  300  GB-months  0.0300       0.0123        9.0000  
  └─ Backup Storage (Multi-AZ)                   -  GB-months  0.0550            -             -  
  Total                                                                     6.9559    5,077.8000  
                                                                                                  
  OVERALL TOTAL (USD)                                                       6.9559    5,077.8000 
```

2020-12-19 21:01 UTC, dawidmalina commented
Thanks @sinabakh great job 👍
Can you point me what does it mean that backup storage can't be supported? Is it related to FSx only or non of the aws backup resources can't be supported?

2020-12-19 22:39 UTC, sinabakh commented
@dawidmalina Thanks.
Sorry I was trying to fix one of our failing unit tests.

The problem is we can now currently support the pricing of resources that have some related quantity value in their terraform file. There is `storage_capacity` for storage and `throughput_capacity` for throughput but I couldn't find such a variable for `Backup storage`.

My initial idea was to take `storage_capacity` for both storage and backup but it seems to be a wrong assumption because you can have incremental backups. Please correct me if I'm wrong.

We are working on our own terraform provider that acts as a supplementary plugin so we can support such cases but it's in its beta stages.

2020-12-20 15:12 UTC, dawidmalina commented
@sinabakh sorry if you took this as a complaints - it was not my intention. Fully agree with your explanation. Once again great job and thank you for that.

2020-12-20 15:14 UTC, sinabakh commented
@dawidmalina Oh no, just wanted to give an in-depth explanation. We hope to support all these parameters soon. Thank you for the detailed issue.

2020-12-21 15:57 UTC, alikhajeh1 requested changes
@sinabakh this is great! Can you possibly rename the cost components to the following to better match the AWS pricing page, but also keep it consistent with other multi-az resource we have (db_instance) that doesn't mention single/multi-az.
```
Throughput capacity 
HDD storage
SSD storage
Backup storage
```

2. The units for throughput capacity is `MBps-month` on the AWS pricing page.
3. It doesn't look like data de-duplication is a flag that can be enabled in terraform, so please mention "Data deduplication is not supported by Terraform." in the notes for the `Notes:` for the resource?

2020-12-21 16:07 UTC, alikhajeh1 commented
@dawidmalina if we add support for this resource in the [Infracost Terraform Provider](https://registry.terraform.io/providers/infracost/infracost/latest/docs), you would be able to add the following block to your terraform project to provide the number of GBs that your `backup_storage` might be, then get a cost estimate for it (vs [this output](https://github.com/infracost/infracost/pull/288#issuecomment-748515940) that shows `-` for the cost since we only know the price). Would you use that in your project? We can do fancy stuff in the future (e.g. by fetching usage data from your cloud account), but for now that's our current answer, and any feedback on it is appreciated :)

```
data "infracost_aws_fsx_windows_file_system" "backup_usage" {
  resources = [aws_fsx_windows_file_system.example.id]
  backup_storage { value = 350 } # in GBs
```

```
  NAME                      MONTHLY QTY  UNIT       PRICE   HOURLY COST  MONTHLY COST  

  aws_fsx_windows_file_system.example                                                             
  ├─ Throughput capacity          1,024  GB-months  4.9500       6.9436    5,068.8000  
  ├─ HDD storage                    300  GB-months  0.0300       0.0123        9.0000  
  └─ Backup storage                1450  GB-months  0.0550       0.1092       79.7500    <<<<< No more dashes, actual cost estimates
  Total                                                          7.0651    5,157.5500  
                                                                                                  
  OVERALL TOTAL (USD)                                            7.0651    5,157.5500 
```

2020-12-21 16:20 UTC, dawidmalina commented
@alikhajeh1 - currently I am watching this project and would like to create small PoC beginning of next year. FSx is one of the resources I was missing and to be honest raw estimation (without usage) is fair enough for me. Definitely it might be very useful in the future but as I said raw estimation based on the resources cost is currently exactly what i am looking for. Thanks for very quick reaction for that missing resource and kudos for the great tool.

2020-12-22 17:34 UTC, sinabakh commented
@alikhajeh1 I tried to fix your comments. Tests failed with unrelated errors, I don't have access to retry them. Also, do we need to fix all codebeat issues, or is it experimental?

2020-12-22 17:48 UTC, aliscott commented
@sinabakh I'll rerun the tests. Please ignore codebeat. Something I tried quickly today and didn't realise it was actually doing this.

2020-12-22 18:16 UTC, alikhajeh1 approved these changes
Thanks @sinabakh!

2020-12-22 18:18 UTC, merged