Adding support for Google Cloud Functions resource
infracost/infracost pull request #399
Opened 2021-02-08 05:37 UTC by ekifel

Issue #311 

```
 NAME                                          MONTHLY QTY  UNIT        PRICE   HOURLY COST  MONTHLY COST  
  google_cloudfunctions_function.function                                                                   
 ├─ CPU Time                                        10,000  GBz-Second   1e-05       0.0001        0.1000  
 ├─ Memory Time                                     10,000  GB-Second    3e-06        3e-05        0.0250  
 ├─ Invocations                                  1,000,000  calls        4e-07       0.0005        0.4000  
 └─ Outbound Data                                      100  GB          0.1200       0.0164       12.0000  
 Total                                                                               0.0172       12.5250  
```

2021-02-10 23:06 UTC, alikhajeh1 requested changes
Awesome! I left my suggestions

2021-02-10 23:06 UTC, alikhajeh1 commented on internal/providers/terraform/google/cloudfunctions_function.go
> +				Name:            "Outbound Data",
```suggestion
				Name:            "Outbound data transfer",
```

2021-02-10 23:06 UTC, alikhajeh1 commented on internal/providers/terraform/google/cloudfunctions_function.go
> +					Region:        strPtr("us-east1"),
```suggestion
					Region:        strPtr(region),
```
?

2021-02-10 23:06 UTC, alikhajeh1 commented on internal/providers/terraform/google/cloudfunctions_function_test.go
> +func TestCloudFunctions(t *testing.T) {
Seems like this needs a _usage test too

2021-02-15 15:30 UTC, ekifel commented
@alikhajeh1 this is ready for review/merge

2021-02-16 10:42 UTC, alikhajeh1 requested changes
Looking good! Two minor changes, sorry I should have spotted those from the pricing page earlier.

2021-02-16 10:42 UTC, alikhajeh1 commented on infracost-usage-example.yml
> +    monthly_outbound_data_gb: 100 # Monthly data transferred from the function out to somewhere else in GB.
```suggestion
    request_duration_ms: 300               # Average duration of each request in milliseconds.
    monthly_function_invocations: 10000000 # Monthly number of function invocations.
    monthly_outbound_data_gb: 100          # Monthly data transferred from the function out to somewhere else in GB.
```

2021-02-16 10:42 UTC, alikhajeh1 commented on internal/providers/terraform/google/cloudfunctions_function.go
> +	requestDuration := decimal.Zero
The pricing page mentions "compute time is measured in 100ms increments, rounded up to the nearest increment" So I think we should:
1. Default this to 100
2. Inside the if-statement, round **up** the user input to the nearest 100ms, e.g. if they provide 240, we set it to 300.

2021-02-16 10:42 UTC, alikhajeh1 commented on internal/providers/terraform/google/cloudfunctions_function.go
> +	invocations := decimal.Zero
This should default to `*decimal.Decimal` as we don't know the number

2021-02-16 21:22 UTC, merged

2021-02-16 21:49 UTC, alikhajeh1 commented
Plz see https://github.com/infracost/infracost/pull/399/commits/23fde606bd1c16e4a4af20fe3be8c607dcb828fa for my changes