Adding support for AWS EventBridge
infracost/infracost pull request #415
Opened 2021-02-10 09:05 UTC by ekifel

Issue #387 

```
  NAME                                          MONTHLY QTY  UNIT       PRICE   HOURLY COST  MONTHLY COST  

  aws_cloudwatch_event_bus.my_events                                                                       
  ├─ Custom published events                              1  1M events  1.0000       0.0014        1.0000  
  ├─ Partner published events                             2  1M events  1.0000       0.0027        2.0000  
  ├─ Events ingested for schema discovery                 3  1M events  0.1000       0.0004        0.3000  
  ├─ Archived events                                 10,000  GB         0.0230       0.3151      230.0000  
  └─ Archive processing                              20,000  GB         0.1000       2.7397    2,000.0000  
  Total                                                                              3.0593    2,233.3000  
```

2021-02-11 11:06 UTC, alikhajeh1 requested changes
Thanks @ekifel - this is great, it's almost there. My suggestions were mostly related to the cost component names/units so plz see that comment first, the rest of the code will need some tweaks based on that. I also left a few tweaks to the filters.

2021-02-11 11:06 UTC, alikhajeh1 commented on internal/providers/terraform/aws/cloudwatch_event_bus.go
> +						{Key: "eventType", Value: strPtr("Discovery Event")},
```suggestion
 						{Key: "usagetype", ValueRegex: strPtr("/Event-8K-Chunks/")},
```
We try to use the usagetype filter where possible (we have some ideas for the future that could use that)

2021-02-11 11:06 UTC, alikhajeh1 commented on internal/providers/terraform/aws/cloudwatch_event_bus.go
> +						{Key: "eventType", Value: strPtr("Partner Event")},
```suggestion
						{Key: "eventType", Value: strPtr("Partner Event")},
						{Key: "usagetype", ValueRegex: strPtr("/Event-64K-Chunks/")},
```
This ensures that in the future if they add other usagetypes for the Partner Event, we'll still find the right one

2021-02-11 11:06 UTC, alikhajeh1 commented on internal/providers/terraform/aws/cloudwatch_event_bus.go
> +						{Key: "eventType", Value: strPtr("Custom Event")},
```suggestion
						{Key: "eventType", Value: strPtr("Custom Event")},
						{Key: "usagetype", ValueRegex: strPtr("/Event-64K-Chunks/")},
```
This ensures that in the future if they add other usagetypes for the Custom Event, we'll still find the right one

2021-02-15 12:41 UTC, ekifel commented
@alikhajeh1 this is ready for review/merge

2021-02-16 10:56 UTC, merged