feat(azure): Add Azure Storage Account (file)
infracost/infracost pull request #694
Opened 2021-05-19 18:49 UTC by NeverovDS

Issue #575 
access_tier : can be only Hot and Cool.

2021-05-20 10:46 UTC, NeverovDS commented
@alikhajeh1 this PR ready to check)

2021-05-20 14:37 UTC, tim775 requested changes

2021-05-20 14:37 UTC, tim775 commented on internal/providers/terraform/azure/storage_account.go
> +		Unit:                 "GB-months",
Use GB instead of GB-months

2021-05-20 14:37 UTC, tim775 commented on internal/providers/terraform/azure/storage_account.go
> +		Unit:                 "GB-months",
GB instead of GB-months

2021-05-20 14:37 UTC, tim775 commented on internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.golden
> + ├─ Capacity                                      Cost depends on usage: $0.04 per GB-months
The branch needs a rebase to pick up the "Monthly cost depends..." output changes.

2021-05-20 14:37 UTC, tim775 commented on internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.golden
> + ├─ Capacity (first 50TB)                                  51,200  GB-months              $7,680.00
I think there is an issue here because storage_gb is set to 1000 TB in the usage file but we're only reporting costs for the first 50TB

2021-05-20 14:37 UTC, tim775 commented on internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.golden
> + ├─ Capacity (first 50TB)                                  51,200  GB-months             $10,240.00
Same issue here?

2021-05-21 10:05 UTC, NeverovDS commented
@tim775 you can check commit

2021-05-21 12:47 UTC, tim775 commented
@alikhajeh1 LGTM

2021-05-21 14:39 UTC, merged